Issue9
cse110-sp24-group35/warmup-exercise pull request #17
Opened 2024-04-25 06:53 UTC by Ant044

Resolves #9 
Splits the dynamically created list items into sets of list items.
Adds button to each list item (Does NOTHING, has no tags, etc)
Adds font
Changes style of text based on priority
I haven't even started lab 4 so I hope I didn't ruin the JS lol\
![image](https://github.com/cse110-sp24-group35/warmup-exercise/assets/146861585/9ebba55d-1bef-4ff5-aa7c-f66aca0b9565)

2024-04-25 21:13 UTC, nadecancode requested changes

2024-04-25 21:13 UTC, nadecancode commented on task-list/index.html
> +    <link href='https://fonts.googleapis.com/css?family=Caveat' rel='stylesheet'>
Didn't we decide to use `Jetbrains Mono` for the team font

2024-04-25 21:13 UTC, nadecancode commented on task-list/style.css
> +#taskItems .listDivOuter{
The class name should be more descriptive in terms of overall implementation instead of in terms of HTML. I recommend something like `taskEntryContainer` (just an example)

2024-04-25 21:13 UTC, nadecancode commented on task-list/style.css
> +#taskItems button{
I recommend to use relative unit for width, height, padding and margin

2024-04-25 21:13 UTC, nadecancode commented on task-list/app.js
> +        li.textContent = `${task.name} `;
Risk for XSS but I guess it's fine for the scope of this app

2024-04-25 21:13 UTC, nadecancode commented on task-list/app.js
> +        tags.textContent = tags.textContent.substring(0, tags.textContent.length-1); // Removes ending comma
More efficient implementation can be utilized here by joining the tags with `,`. Also there's redundant mutation of DOM element which is highly discouraged due to performance issues

2024-04-26 06:00 UTC, nadecancode requested changes

2024-04-26 06:00 UTC, nadecancode commented on task-list/app.js
> +        tags.textContent = ` - Tags: ${task.tags}`;
If I'm not mistaken, you're trying to serialize an entire JS array as string? I was more like referring to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join when I was talking about joining

2024-04-26 06:00 UTC, nadecancode commented on task-list/app.js
> +        tags.textContent = ` - Tags: ${task.tags}`;
Otherwise it'll be a straight stringified representation of the array like `[1, 2, 3]` instead of `1, 2, 3`

2024-04-26 06:01 UTC, Ant044 commented on task-list/app.js
> +        li.textContent = `${task.name} `;
Not quite sure what should be done instead. Still haven't finished lab 4 😔

2024-04-26 06:02 UTC, nadecancode commented on task-list/app.js
> +        li.textContent = `${task.name} `;
Possibly not in the scope of this class, don't worry about it

2024-04-26 06:03 UTC, Ant044 commented on task-list/app.js
> +        tags.textContent = ` - Tags: ${task.tags}`;
I'm not sure about the technicality of it but it seems to look the same?
![image](https://github.com/cse110-sp24-group35/warmup-exercise/assets/146861585/b1a60f91-ce53-46f1-a5ea-db6b35f96e52)
![image](https://github.com/cse110-sp24-group35/warmup-exercise/assets/146861585/d98626fd-b94c-4543-8c8c-dbdbb7f5625e)

2024-04-26 06:05 UTC, nadecancode commented on task-list/app.js
> +        tags.textContent = ` - Tags: ${task.tags}`;
Weird, it technically should be a direct stringified ver of array. I'll approve this and it goes wacky in prod then I'll fix

2024-04-26 06:06 UTC, nadecancode approved these changes

2024-04-26 06:06 UTC, merged